### ISSUE TITLE
Escrow: development of smart contract UI/UX

### ISSUE THREAD

**Issue by iBuildApp** [iBuildApp/dApp-Builder#36]
See [specification here](/iBuildApp/dApp-Builder/wiki/Whitepaper#bettingescrow)

development of smart contract UI/UX necessary to create a new structure in the contract (new instance of the dApp)

**Comment by constfilin** [comment]
There are several problems with the [current version](https://github.com/iBuildApp/dApp-Builder/blob/master/dApp%20Builder%20smart%20contracts/ibaEscrow.sol) of Escrow contract
1. **ibaEscrow** - let's rename this to **dabEscrow** (dApp Builder Escrow)
1. There seems to be a **HUGE** error in [refund method](https://github.com/iBuildApp/dApp-Builder/blob/master/dApp%20Builder%20smart%20contracts/ibaEscrow.sol#L111) because it does not check the current status of the bid. It looks like **buyer**  can call this method numerous times after the expiration of limited contract and each time he will be receiving the refund equal to the price of the contract (as long as there are any funs in the Escrow contract). Hm...
1. In [refund method](https://github.com/iBuildApp/dApp-Builder/blob/master/dApp%20Builder%20smart%20contracts/ibaEscrow.sol#L111) the oracle should not receive the fee (i.e. all the fee should go to the buyer). This is because:
    1. In these scenarios oracle does nothing and should not receive the fee
    1. we need to prevent abuse of escrow contracts where Oracles get lots of fee without doing anything
